version: '3.8'

services:
  backend: # Definição do serviço Backend
    build: # Configuração para construir a imagem do backend
      context: . # Diretório onde está localizado o Dockerfile
      target: backend # Especificação do alvo para a construção (backend)
      dockerfile: Dockerfile-backend # Nome do Dockerfile para o backend
    ports:
      - "8080:80" # Mapeamento da porta 8080 do host para a porta 80 do contêiner
    environment:
      - APP_KEY=sua_chave_do_aplicativo # Variável de ambiente para a chave do aplicativo
    # Outras configurações necessárias para o backend

  frontend: # Definição do serviço Frontend
    build: # Configuração para construir a imagem do frontend
      context: . # Diretório onde está localizado o Dockerfile
      target: frontend # Especificação do alvo para a construção (frontend)
      dockerfile: Dockerfile-frontend # Nome do Dockerfile para o frontend
    ports:
      - "8081:3000" # Mapeamento da porta 8081 do host para a porta 80 do contêiner
    # Outras configurações necessárias para o frontend

  db: # Definição do serviço de Banco de Dados (PostgreSQL)
    image: postgres:latest # Imagem utilizada para o serviço (última versão do PostgreSQL)
    restart: always # Sempre reiniciar o serviço se ele parar inesperadamente
    environment:
      POSTGRES_USER: workana # Usuário do PostgreSQL
      POSTGRES_PASSWORD: Teste@teste # Senha do PostgreSQL
      POSTGRES_DB: workana-softexpert # Nome do banco de dados
    ports:
      - "5432:5432" # Mapeamento da porta 5432 do host para a porta 5432 do contêiner
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência dos dados do PostgreSQL

volumes:
  postgres_data: # Definição do volume para persistência dos dados do PostgreSQL
