# Use a imagem base do Debian
FROM debian:buster

# Atualize os pacotes e instale o que é necessário para o ambiente do Laravel
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    postgresql \
    php php-fpm php-pgsql php-mbstring

# Instalação do PostgreSQL e suas dependências
RUN apt-get install -y postgresql postgresql-contrib

# Configuração do PHP
RUN sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php/7.3/fpm/php.ini

# Instale o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Defina o diretório de trabalho como o diretório do aplicativo Laravel (ajuste conforme necessário)
WORKDIR /var/www/html

# Exponha a porta 8000 para acesso ao servidor embutido do Laravel
EXPOSE 8000

# Comando para iniciar o servidor embutido do Laravel
CMD php artisan serve --host=0.0.0.0 --port=8000
